// ════════════════════════════════════════════════════════════════════════════
// § DOMAIN: chat session (server-held conversation)
// ════════════════════════════════════════════════════════════════════════════
//
// Decision 16 (2026-10-01): the server remembers what was actually said. The
// browser sends only a server-issued session id (the "ticket"), never the
// conversation, so a visitor cannot forge earlier turns. Messages are held in
// chat_sessions:
//   * a chat that reaches a handoff has its messages copied onto the alert
//     record (lead_alerts.transcript) and the held row is deleted;
//   * every other chat's held messages are discarded after CHAT_SESSION_IDLE_HOURS
//     of idle time (Decision 19: option B; 4 hours is the working value),
//     counted from the visitor's last message.
//
// The ticket is the row's session_id, generated by the database (a random
// UUID). A ticket that is missing, malformed, unknown, expired, or issued for a
// different page is not an error: the visitor simply starts a fresh chat with no
// memory, and a new ticket is returned.

import { supabaseFetch, supabasePatchByField, supabasePost, supabaseRpc } from "./supabase.js";

export const DEFAULT_IDLE_HOURS = 4;
// Held turns kept per chat. A chat this long is not a normal visit; the oldest
// turns fall away rather than letting one row grow without bound.
export const MAX_HELD_TURNS = 200;
// How many recent turns the model is shown as history.
export const MODEL_HISTORY_TURNS = 10;

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export function idleHours(env) {
  const n = Number(env?.CHAT_SESSION_IDLE_HOURS);
  return Number.isInteger(n) && n >= 1 ? n : DEFAULT_IDLE_HOURS;
}

function normalize(row) {
  return {
    session_id: row.session_id,
    page: row.page,
    conversation: Array.isArray(row.conversation) ? row.conversation : [],
    flow_state: row.flow_state ?? "chat",
    flow_data: row.flow_data && typeof row.flow_data === "object" ? row.flow_data : {},
  };
}

// Returns the visitor's held session, or starts a new one. Never throws on a bad
// ticket; throws only if the database cannot be reached (the caller fails the turn).
export async function loadOrStartSession(env, ticket, page) {
  if (typeof ticket === "string" && UUID_RE.test(ticket)) {
    const rows = await supabaseFetch(env, "chat_sessions",
      `?session_id=eq.${encodeURIComponent(ticket)}&select=session_id,page,conversation,flow_state,flow_data,last_active_at`);
    const row = rows?.[0];
    if (row) {
      const ageMs = Date.now() - new Date(row.last_active_at).getTime();
      const expired = !(ageMs < idleHours(env) * 3600 * 1000);
      if (expired) {
        // Past its idle limit: discard it now rather than waiting for the sweep.
        await discardSession(env, ticket)
          .catch((e) => console.error("expired session discard failed:", e));
      } else if (row.page === page) {
        return { session: normalize(row), fresh: false };
      }
    }
  }
  const created = await supabasePost(env, "chat_sessions", { page });
  const row = created?.[0];
  if (!row?.session_id) throw new Error("chat session could not be created");
  return { session: normalize({ ...row, conversation: row.conversation ?? [] }), fresh: true };
}

// Appends turns and records the flow position. The write resets the idle clock.
export async function saveSession(env, session, { turns = [], flow_state, flow_data }) {
  const held = [...session.conversation, ...turns].slice(-MAX_HELD_TURNS);
  const next = {
    conversation: held,
    flow_state: flow_state ?? session.flow_state,
    flow_data: flow_data ?? session.flow_data,
    last_active_at: new Date().toISOString(),
  };
  await supabasePatchByField(env, "chat_sessions", "session_id", session.session_id, next);
  return { ...session, ...next };
}

// Discards a held chat. The database removes the row, or empties it when a
// proposal or review item still points at it (see migration 019).
export async function discardSession(env, sessionId) {
  await supabaseRpc(env, "discard_chat_session", { p_session_id: sessionId });
}
export { discardSession as deleteSession };

// What the model is shown as prior turns: only what was said in the ordinary
// chat. Contact-collection turns (flow: true) are left out so a visitor's
// details are never fed back into a generation call.
export function modelHistory(conversation, maxTurns = MODEL_HISTORY_TURNS) {
  return (Array.isArray(conversation) ? conversation : [])
    .filter((t) => t && !t.flow && (t.role === "user" || t.role === "assistant") && typeof t.content === "string")
    .slice(-maxTurns)
    .map((t) => ({ role: t.role, content: t.content }));
}

// The conversation as stored on a handoff record: every turn, in order, each
// labelled by role. Plain data, no flags.
export function transcriptFor(conversation) {
  return (Array.isArray(conversation) ? conversation : [])
    .filter((t) => t && (t.role === "user" || t.role === "assistant") && typeof t.content === "string")
    .map((t) => ({ role: t.role, content: t.content }));
}

// Scheduled sweep (worker `scheduled` handler). Idempotent; the load path above
// already discards a session the moment it is found expired.
export async function discardIdleChatSessions(env) {
  const n = await supabaseRpc(env, "discard_idle_chat_sessions", { p_idle_hours: idleHours(env) });
  return typeof n === "number" ? n : 0;
}
